sudo: required
dist: bionic

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
    - build-essential 
    - libboost-all-dev

  homebrew:
    update: true
    packages:
    - cmake
    - qt5
    - boost

os:
  - linux

env:
  global:
    - YARP_BRANCH="devel"
  matrix:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release


before_script:
  #ubuntu dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install cmake qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5opengl5-dev libqcustomplot-dev libeigen3-dev; fi
  # macOS dependencies
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap robotology/cask; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install --only-dependencies yarp; fi
  # Setup the YARP branch 
  - export YARP_BRANCH="devel" && echo "Using yarp devel branch"
    #install yarp
  - git clone --depth 1 --branch=devel  https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=OFF -DCREATE_LIB_MATH:BOOL=ON
  - make
  - sudo make install
  - cd ../..
   
  #Blocktest
  - qmake --version
  - cmake --version

script:
  # configure rfsmTools
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

notifications:
  email:
    - luca.tricerri@iit.it
