sudo: required
dist: xenial

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
    - build-essential 
    - qtcreator 
    - qt5-default 
    - libboost-all-dev

  homebrew:
    update: true
    packages:
    - cmake
    - qt

os:
  - linux
  - osx

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release


before_script:
    #install yarp
  - git clone --depth 1 -b $YARP_BRANCH https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer_carrier:BOOL=ON -DENABLE_icubmod_usbCamera:BOOL=ON -DENABLE_icubmod_usbCameraRaw:BOOL=ON
  - make
  - sudo make install
  - cd ../..
   
  #Blocktest
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi
  - qmake --version
  - cmake --version

script:
  # configure rfsmTools
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

notifications:
  email:
    - luca.tricerri@iit.it