sudo: required
dist: xenial

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
    - build-essential 
    - qtcreator 
    - qt5-default 
    - libboost-all-dev

  homebrew:
    update: true
    packages:
    - cmake
    - qt

os:
  - linux
  - osx

env:
  global:
    - YARP_BRANCH="devel"
  matrix:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release


before_script:
#ubuntu dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --assume-yes --force-yes install cmake libeigen3-dev icub-common libv4lconvert0 libv4l-dev; fi
  # Setup the YARP branch 
  - if [ "$TRAVIS_BRANCH" = "devel" ] ; then export YARP_BRANCH="devel" && echo "Using yarp devel branch" ; fi
    #install yarp
  - git clone --depth 1 --branch=devel  https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer_carrier:BOOL=ON -DENABLE_icubmod_usbCamera:BOOL=ON -DENABLE_icubmod_usbCameraRaw:BOOL=ON
  - make
  - sudo make install
  - cd ../..
   
  #Blocktest
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi
  - qmake --version
  - cmake --version

script:
  # configure rfsmTools
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

notifications:
  email:
    - luca.tricerri@iit.it