sudo: required
dist: bionic

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
    - build-essential 
    - qtbase5-dev
    - qtdeclarative5-dev
    - qtmultimedia5-dev
    - libqt5opengl5-dev
    - libqcustomplot-dev
    - libboost-all-dev
    - libace-dev
    - libeigen3-dev

  homebrew:
    update: true
    packages:
    - cmake
    - ace
    - sqlite
    - tinyxml
    - libedit
    - qt5
    - eigen

os:
  - linux

env:
  global:
    - YARP_BRANCH="devel"
  matrix:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release


before_script:
  #ubuntu dependencies
  #- sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list';
  - sudo apt-get update;
  - sudo apt-get --assume-yes --force-yes install cmake libeigen3-dev libv4lconvert0 libv4l-dev;
  # Setup the YARP branch 
  - export YARP_BRANCH="devel" && echo "Using yarp devel branch"
    #install yarp
  - git clone --depth 1 --branch=devel  https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=OFF -DCREATE_LIB_MATH:BOOL=ON
  - make
  - sudo make install
  - cd ../..
   
  #Blocktest
  - qmake --version
  - cmake --version

script:
  # configure rfsmTools
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

notifications:
  email:
    - luca.tricerri@iit.it
