name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      superbuild_release:
        description: 'Robotology Superbuild Release'
        required: true
        default: 'master'
      blocktest_release:
        description: 'Blocktest Release'
        required: true
        default: 'devel'
      blocktest_yarp_plugins_release:
        description: 'Blocktest YARP Plugins Release'
        required: true
        default: 'master'
      blocktest_ros_plugins_release:
        description: 'Blocktest ROS Plugins Release'
        required: true
        default: 'master'
      add_tag_latest:
        type: boolean
        description: 'Add tag latest to the docker image'
        required: true
        default: true
      build_type:
        type: choice
        description: 'Build Type'
        options:
        - 'Release'
        - 'Debug'
        required: true
        default: 'Release'  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Require tag latest
      id: add_tag_latest
      if: ${{ inputs.add_tag_latest }}
      run: |
        echo "tag=, latest" >> $GITHUB_OUTPUT
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      env:
        ROBOTOLOGY_SUPERBUILD_RELEASE: ${{ inputs.superbuild_release }}
        BLOCKTEST_RELEASE: ${{ inputs.blocktest_release }}
        BLOCKTEST_YARP_PLUGINS_RELEASE: ${{ inputs.blocktest_yarp_plugins_release }}
        BLOCKTEST_ROS_PLUGINS_RELEASE: ${{ inputs.blocktest_ros_plugins_release }}
        BUILD_TYPE: ${{ inputs.build_type }}
      with:
        name: robotology/blocktest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        workdir: dockerfiles
        buildargs: ROBOTOLOGY_SUPERBUILD_RELEASE, BLOCKTEST_RELEASE, BLOCKTEST_YARP_PLUGINS_RELEASE, BLOCKTEST_ROS_PLUGINS_RELEASE, BUILD_TYPE
        registry: ghcr.io
        tags: "${{ inputs.superbuild_release }}_${{ inputs.blocktest_release }}${{ steps.add_tag_latest.outputs.tag }}"
